/*
Project Euler: Problem 02
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

function p2_calc() {
	var input = Number(document.getElementById("p2_input").value);
	var sum = 0;
	var x = 1;
	var y = 1;
	var z = 0;

	if(isNaN(input)) {
		document.getElementById("p2_output").innerHTML = "That's not a number!";
	}
	else if (input < 0) {
		document.getElementById("p2_output").innerHTML = "Positive Numbers Please!"
	}
	else {
		do {
			if(x%2 === 0) {
				sum += x;
			};

			z = x + y;
			y = x;
			x = z;
		}
		while (x <= input);
		document.getElementById("p2_output").innerHTML = "Answer: "+sum;
	};
};